### ISSUE TITLE
Canțt install addon

### ISSUE THREAD

**Issue by vladblindu** [proxeIO/namestack#13]
I use the Blender 2.8 beta Mac-os release.
This is the version:
![Screen Shot 2019-07-28 at 16 05 13](https://user-images.githubusercontent.com/46263775/62007194-3ae50400-b153-11e9-9b7e-8667c9fedfcb.png)
Tis is the error:
![Screen Shot 2019-07-28 at 16 04 01](https://user-images.githubusercontent.com/46263775/62007213-6b2ca280-b153-11e9-90e6-cd82c4479ce7.png)

It's true I only payed 1 dollar, but still....:)

**Comment by proxeIO** [comment]
The addon in this repo is for 2.79

2.80 version is a rework from the ground up. I am currently working on restoring batch naming, and moving out of beta for it. You can get it on my site [proxe.io](https://proxe.io/store/d8pq/ns), [grumroad](https://gumroad.com/l/namestack) or [blender market](https://blendermarket.com/products/nS)

Sorry for any confusion.
