### ISSUE TITLE
[Q]How can the find add suffix only for found text? Using vertexgroups

### ISSUE THREAD

**Issue by schroef** [proxeIO/namestack#7]
v 0.8
bl 2.79
osx

First of all what a sweet time saving addon!!! It already saved me quite a lot. I was testing this rig from Mixamo and noticed the rig and the mesh had different vertex names. I could easily rename the bones and finding and adding a suffix. Yet when i try to find a text, delete a part and add a suffix with vertex groups its adds the suffix to all?

**Comment by schroef** [comment]
Ahh i got it, i need to filter them and than do the batch rename, sweet!!!! this is so easy now

**Comment by proxeIO** [comment]
Sorry about the late response, just noticed the issue, I will look into adding a toggle for the behavior.

**Comment by schroef** [comment]
Yes, i dont understand why no one asked for it earlier. Seems quite standard looking at the other functions already there. I tried to add it myself. But couldnt get it to work

**Comment by proxeIO** [comment]
Just pushed the new behavior, let me know what you think, it is enabled by default. and effects custom name, prefix, suffix, trim start, trim end, and cutting, currently not sorting or counting however.

https://blenderartists.org/t/addon-name-stack-0-8/556738/588?u=proxe

**Comment by schroef** [comment]
Ill test it immediately

**Comment by schroef** [comment]
Sweet works like a charm. One thing, but perhaps that is not proper workflow. When we initially do the filter in the Properties panel. We than do an Batch action, but here we need to apply again the filter. 

Does it make sense to link these 2 or make them 1?

In the batch action there are more options to filter though. I can click the batch immediatly ofcourse and than only filter it there.

Filter Menu batch panel
<img width="385" alt="screen shot 2018-10-08 at 17 52 58" src="https://user-images.githubusercontent.com/6923008/46635684-3ea38d80-cb23-11e8-8343-f01c98ecad6b.png">

Filter Menu normal panel
<img width="291" alt="screen shot 2018-10-08 at 17 52 52" src="https://user-images.githubusercontent.com/6923008/46635685-3ea38d80-cb23-11e8-946d-5fdc0f128b35.png">

**Comment by schroef** [comment]
PS i do see an error now, i opened a different scene and noticed this in the console.

`location: <unknown location>:-1
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/namestack/addon/interface/name.py", line 49, in draw
    main(self, context)
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/namestack/addon/interface/name.py", line 97, in main
    populate(self, context, layout, datablock, panel)
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/namestack/addon/interface/name.py", line 878, in populate
    block.objectData.material(self, context, column, object, panel)
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/namestack/addon/interface/name.py", line 1491, in material
    textures = [tslot.texture.name for tslot in slot.material.texture_slots if hasattr(tslot, 'texture')]
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/namestack/addon/interface/name.py", line 1491, in <listcomp>
    textures = [tslot.texture.name for tslot in slot.material.texture_slots if hasattr(tslot, 'texture')]
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1
`

**Comment by proxeIO** [comment]
Fixed, thanks for the help! I will look into making the transition from panel to batch naming more seamless, perhaps a user preference for batch name, 'inherit filters from panel' or something along those lines

**Comment by schroef** [comment]
Yes, perhaps that helps. I understand its more difficult than this because the batch operation has much more inputs.

**Comment by proxeIO** [comment]
The main issue I see using the props from the panel directly is that changing them would effect what is displayed in the panel, Which I think could be annoying if you spent some time filtering and searching for what you want to be displayed and having it changed each batch operator

Not sure I have seen an addon with as many props in it, over 250

Inheriting the prop values though is something that can be done at invoke, for batch name, making it a fairly pleasant process.

**Comment by schroef** [comment]
Perhaps im just making this confusing. I tend to first filter and than do the batch. I think that is not the proper workflow right?

**Comment by proxeIO** [comment]
it used to be, carrying the property values over however is fairly trivial, there used to be a batch namer that only effected the name stack itself, with this carrying behavior the result is essentially the same.

off topic, however i have been watching the thread for kitops smart inserts

just to clarify the difference between, hops, meshmachine plugs and kitops, is that both hops and meshmachine share and inserting system that was essentially first created if im not mistaken by [Jacques Lucke](https://github.com/JacquesLucke), at the very least they are based on very similar systems that he created.

I wrote kitops from the ground up to be able to be the simplest approach so far, as close to possible as a drag and drop interaction with blender in regards to quickly dropping booleans, and having those cuts displayed immediately

neither hops nor meshamachine currently immedietly perform the cut, both rely on blenders internal snapping mechanisms, and always require and extra level of input by the user, such as pressing G, holding CTRL and after clicking the insert, then clicking an apply button.

kitops uses a ray tracing solution, never interfering with you current 3d view options

in addition the toggle options in kitops are incredibly intuitive, allowing for dynamic behavior and visual clarity as far as the interface on what it is precisely that you can see in the viewport.

to take this a step further kitops also includes automatic selection of inserts, which can be any number of objects or object types

indeed an insert file can allow for full drag and drops of the scene you created in the file itself, granted you take the time to set up the cutters and put what you want on layer 1, this includes fully rigged characters, with immediate animation feedback if desired.

kitops will also automatically perform many tasks as you work in smart mode, with auto select, selecting an insert, which can be any number of objects, or duplicating immediately creates a new modifier for the new insert's cutter, which can be 60 if you desire to have so many.

the ease of set up for insert files is a huge bonus, kitops is really designed to be the best at what it does, and with much potential to be had in the future.

just letting you in on some insider info, here, as i do not want to interfere with Chipp's desires in regards to how or when the tool is represented in the community.
